/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '@angular/core';
import * as i1 from './http-wrapper.module';
import * as i2 from '@angular/http';
import * as i3 from './http-wrapper';
export const HttpWrapperModuleNgFactory:i0.NgModuleFactory<i1.HttpWrapperModule> = i0.ɵcmf(i1.HttpWrapperModule,
    ([] as any[]),(_l:any) => {
      return i0.ɵmod([i0.ɵmpd(512,i0.ComponentFactoryResolver,i0.ɵCodegenComponentFactoryResolver,
          [[8,([] as any[])],[3,i0.ComponentFactoryResolver],i0.NgModuleRef]),i0.ɵmpd(4608,
          i2.BrowserXhr,i2.BrowserXhr,([] as any[])),i0.ɵmpd(4608,i2.ResponseOptions,
          i2.BaseResponseOptions,([] as any[])),i0.ɵmpd(5120,i2.XSRFStrategy,i2.ɵb,
          ([] as any[])),i0.ɵmpd(4608,i2.XHRBackend,i2.XHRBackend,[i2.BrowserXhr,i2.ResponseOptions,
          i2.XSRFStrategy]),i0.ɵmpd(4608,i2.RequestOptions,i2.BaseRequestOptions,([] as any[])),
          i0.ɵmpd(5120,i2.Http,i2.ɵc,[i2.XHRBackend,i2.RequestOptions]),i0.ɵmpd(4608,
              i3.HttpWrapper,i3.HttpWrapper,[i2.Http]),i0.ɵmpd(512,i2.HttpModule,i2.HttpModule,
              ([] as any[])),i0.ɵmpd(512,i1.HttpWrapperModule,i1.HttpWrapperModule,
              ([] as any[]))]);
    });
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL1VzZXJzL2Rha28vYnJpaXNrL25nMi9odHRwLXdyYXBwZXIvc3JjL2FwcC9odHRwLXdyYXBwZXIvaHR0cC13cmFwcGVyLm1vZHVsZS5uZ2ZhY3RvcnkudHMiLCJ2ZXJzaW9uIjozLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJuZzovLy9Vc2Vycy9kYWtvL2JyaWlzay9uZzIvaHR0cC13cmFwcGVyL3NyYy9hcHAvaHR0cC13cmFwcGVyL2h0dHAtd3JhcHBlci5tb2R1bGUudHMiXSwic291cmNlc0NvbnRlbnQiOlsiICJdLCJtYXBwaW5ncyI6IkFBQUE7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7OzsifQ==
